# Generated by Django 4.1.2 on 2022-10-07 04:28

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mamografia',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('imagem', models.CharField(max_length=255)),
                ('imagem_processada', models.CharField(blank=True, max_length=255)),
                ('rotulo', models.CharField(max_length=255)),
                ('processado', models.BooleanField(default=False)),
                ('classificado', models.BooleanField(default=False)),
                ('tem_tumor', models.BooleanField(blank=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_processamento', models.DateTimeField(blank=True)),
                ('data_classificacao', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'mamografias',
                'ordering': ['data_envio'],
            },
        ),
    ]
